language: node_js
node_js: node
install:
- npm install
script:
- npm run travis
env:
  global:
    secure: B1vCGy3kThEyfNL+r/ec9yGvXaL6GOXYVkA0arnbTU3BMVcjZitV8ajZdvioL8JNrPtPSpWTc+qotTQmH8XKhbxriVfVynzIqq+bNsBCJFbiafi2l4CZANCRl/9SpFbYINTxIKwdYJfryIdxcL+G1L0zkIhXlbw1SGIAlNmEbBFR/PEoPxXREA5wFL4NjYRH4NNhd8nRpwPGwdPW3g8c78q+iOe+Nen2g3op4mhmBlr3axpEUKixcjjBNlP6Un52DC7grm1wKuq2Wf6EioKuVbB8E2my6JQBcXfobrArID5lo9bt+nb3qJJt/44kIyjqUJOLkraEESR3zlsvzBHMZ548hAiX4YdpNQ1T7u/Igq6zHKzA6YtXqLTpyO3OzEur4EUtp8oEqspP8pGiGit1YDhTSCNUlWWJZqjzTmIGhE5MdnUGGdpAzT+x6IUuOxwTnmpfMKrCqraJia1iSpgVq2bnLCTbc1+hphM9JGurMSoY9apfOXqz7BztTDMimpkA6g9ZNhJBDbvILVkjFNnt7K+NOnj1SOHDx09E2SuGGv4wtjO7mzqi+TZnqIf8IQotlv3WEk1GOVT3PCLwQjeWW3iYuN3zdz7HB6ErF1M4CeCHzUfLWCKudM9bByhIBYdde9wkAmqJXd+l0p1UbLDbVCtRYlWNYr66Ge5q5OEaNkk=
deploy:
  provider: npm
  email: zouxuoz@gmail.com
  skip_cleanup: true
  api_key:
    secure: keRxiWTAuYvxnyOBs30z2Wr5OAEeq11IiCPVt9okP4qfki1y9/wg7xS+WL2iHPAmiJt/4Nks/vqFdwLHl0rRMw9IoMX4D6fjggrvdfQNkosvdPm2ToYYC2Y4CqOYJLVAgzuCvAWlJaIqUxYyOpV4d/4Lu2KBy390DrvKLCsSN9xISmPs+3TXvfUPe8+5i/aMclDps9KP11L0XOwfZVjtfk4/H6lB1NjyPsgEGMiqc9vmXqn+oDIpHspft6Lp8Dm9GtSVhJhG8uJu+5k6009NT1opcvmxYSwXjZ88702KKlAAh/ysWIJho1tVRO/f/ePKA9Zm90xXjvqD7y/HMH9+qPYcO59OnLc6BOGX2SxIo8rVZgZ5HR9FOTWaaLxwINDrcLtoTDWZ69VYSnpknNI3g/kXK5hbHNn13PHK3QyGU4hx0hAY8TbQ5xgYRfqshK4GH9SZZNNDxRzKrbATTZube4FtKiM/Omj+VtisGujPVM3SnYXTu4hiel7jysZgBre6YAqKDiO+w//sK2tf/+ySqfFCUb/R0EKAuMEpKSypvbjzrBTpmm0Kq2b42l1kwMgHXMWEkJOujZ7cL9EuvmcF4e6XQlMzhU6AQ7tEuRjRajezEAEOZLPRrDPA7e5tZAV6QRh21a1Nr7A8JPsJ/HF3lEEQNN2CYpYJ4fSlU57rrPY=
  on:
    tags: true
    repo: zouxuoz/test-inbox
    branch: master
