language: node_js
node_js: node
install:
- npm install
script:
- npm run travis
- npm run build
env:
  global:
    secure: B1vCGy3kThEyfNL+r/ec9yGvXaL6GOXYVkA0arnbTU3BMVcjZitV8ajZdvioL8JNrPtPSpWTc+qotTQmH8XKhbxriVfVynzIqq+bNsBCJFbiafi2l4CZANCRl/9SpFbYINTxIKwdYJfryIdxcL+G1L0zkIhXlbw1SGIAlNmEbBFR/PEoPxXREA5wFL4NjYRH4NNhd8nRpwPGwdPW3g8c78q+iOe+Nen2g3op4mhmBlr3axpEUKixcjjBNlP6Un52DC7grm1wKuq2Wf6EioKuVbB8E2my6JQBcXfobrArID5lo9bt+nb3qJJt/44kIyjqUJOLkraEESR3zlsvzBHMZ548hAiX4YdpNQ1T7u/Igq6zHKzA6YtXqLTpyO3OzEur4EUtp8oEqspP8pGiGit1YDhTSCNUlWWJZqjzTmIGhE5MdnUGGdpAzT+x6IUuOxwTnmpfMKrCqraJia1iSpgVq2bnLCTbc1+hphM9JGurMSoY9apfOXqz7BztTDMimpkA6g9ZNhJBDbvILVkjFNnt7K+NOnj1SOHDx09E2SuGGv4wtjO7mzqi+TZnqIf8IQotlv3WEk1GOVT3PCLwQjeWW3iYuN3zdz7HB6ErF1M4CeCHzUfLWCKudM9bByhIBYdde9wkAmqJXd+l0p1UbLDbVCtRYlWNYr66Ge5q5OEaNkk=
deploy:
  provider: npm
  email: zouxuoz@gmail.com
  skip_cleanup: true
  api_key:
    secure: bw7s6Vwg0TX1TWDk0HTd6WgP+JVIcug8s3TTJ05IyPfnKt/vSc8LI0WEUrkMm1IV13Q39AAzv309uMQ1kfkfsbGJt6GK99jEp0LrUQBq43GuENZ6BXWEl3aR1OTV+jUU+QqDyJmmSpAEdrxvIUTtUK4DWzvVuJskt2nMF+I+DqFCBY9tHsfVPm6A9puMZtOGzRTonMB1zBi4eLrUE3PiUjs0QC909u6UDhEyMdSDGTNgeh4Dx9oLGWTk/OSnfkk0crC83RlOg52ELvbIqxfbNSa0gbCgFqBkA3m0ngeraGfxzgkuBviNTQhvqi1QaAguJ/7XURp9c2GYjCsgZaJZAfDU0VtPWadigNBvCq0Fgr2WgmRQ9k9cdD0954C83nbe8gDnTxyRmipKrk3RYzfv8iY3BfOKoCQp4VXnlA2Uo6zBxL3mDo3amTCclqZACSq1zIdMjkPZSEcxCcXLR2wJFDx7Ov4Ab/nOG68Sm7FR1kLhC7SuEKz7jtlRoXkU9ItjsrJav6UmIx03756MA19WEsRe5ldtcRfpuYxraDtNuhPU4Sm5qLTe+z6R+RJ38nvNGOWVurBB9NlfOZlwLnlHbF9SJ6L9tGOxiKLYsI0yGT4hPbdXMasIiGXAH6F+meKLLAFOvQLPI3OpCKiOQjvinGxSI1oLuJBbe3Sh9V59oB0=
  on:
    tags: true
    repo: zouxuoz/test-inbox
    branch: master
